# Based on typst's release action:
# https://github.com/typst/typst/blob/main/.github/workflows/release.yml

name: Release
on:
  release:
    types: [published]

jobs:
  build-release:
    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: x86_64-linux
            target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
          - name: i686-linux
            target: i686-unknown-linux-musl
            os: ubuntu-latest
            cross: true
          - name: aarch64-linux
            target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            cross: true
          - name: armv7-linux
            target: armv7-unknown-linux-musleabi
            os: ubuntu-latest
            cross: true
          - name: riscv64gc-linux
            target: riscv64gc-unknown-linux-gnu
            os: ubuntu-latest
            cross: true
          - name: x86_64-darwin
            target: x86_64-apple-darwin
            os: macos-latest
            cross: false
          - name: aarch64-darwin
            target: aarch64-apple-darwin
            os: macos-latest
            cross: false

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@4305c38b25d97ef35a8ad1f985ccf2d2242004f2
        with:
          target: ${{ matrix.target }}

      - name: Run Cross
        if: ${{ matrix.cross }}
        run: |
          cargo install cross --git https://github.com/cross-rs/cross.git --locked --rev 88f49ff7
          cross build --release --target ${{ matrix.target }}

      - name: Run Cargo
        if: ${{ !matrix.cross }}
        run: cargo build --release --target ${{ matrix.target }}

      - name: create artifact directory
        shell: bash
        run: |
          directory=gexport-${{ github.event.release.tag_name }}-${{ matrix.name }}
          mkdir $directory
          cp README.md LICENSE $directory
          cp target/${{ matrix.target }}/release/gexport $directory
          tar cJf $directory.tar.xz $directory

      - uses: ncipollo/release-action@bcfe5470707e8832e12347755757cec0eb3c22af
        with:
          artifacts: "gexport-${{ github.event.release.tag_name }}-${{ matrix.name }}.*"
          allowUpdates: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true

  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@02cc2f1ad653fb25c7d1ff9eb590a8a50d06186b
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
